import {Textfit} from "@ataverascrespo/react18-ts-textfit"
import "./cards.scss"
// import {Lock} from "../utils"
import {uniqueId} from "../utils"
import {AbstractCard, BlackCard, WhiteCard} from "../state"

// parsing and rendering of the card markup, as generated by convert_cards.py
const processCardText = (text: string, blackCard: boolean) => {
  const processedText: any[] = []
  let currentWord: any[] = []
  let currentHasBlank = false
  let currentPart = ""
  let currentItalic = false

  const endPart = () => {
    if (currentPart.length) {
      currentWord.push(currentItalic ? <em key={currentWord.length}>{currentPart}</em> : currentPart)
      currentPart = ""
    }
  }
  const endWord = () => {
    endPart()
    if (currentWord.length) {
      if (blackCard) {
        processedText.push(
          <span className={`word ${currentHasBlank ? "blank" : ""}`} key={processedText.length}>{currentWord}</span>,
        )
      } else {
        processedText.push(...currentWord)
      }
      currentWord = []
      currentHasBlank = false
    }
  }
  for (let i = 0; i < text.length; i++) {
    let char = text[i]
    if (char === "\\") {
      const escaped = text[++i]
      if (blackCard && escaped === "_") {
        endPart()
        currentWord.push(<span className="blank" key={currentWord.length}>&nbsp;</span>)
        currentHasBlank = true
        continue
      } else if (escaped === "I" || escaped === "i") {
        endPart()
        currentItalic = escaped === "I"
        continue
      } else {
        char = escaped
      }
    }
    if (blackCard && char === " ") {
      endWord()
    } else {
      currentPart += char
    }
  }
  endWord()
  return processedText
}

interface CardProps<C extends AbstractCard> {
  card: C
  scale?: number
}

// TODO: learn how to fix this no-empty-object-type
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface BlackCardViewProps extends CardProps<BlackCard> {}

export const BlackCardView = ({ card, scale }: BlackCardViewProps) => {

  if (scale === undefined)
    scale = 1

  let drawPick = null
  if (card.drawCount !== 0) {
    drawPick =
      <div className="draw-pick">
        <div>DRAW <span className="number"><span>{card.drawCount}</span></span></div>
        <div>PICK <span className="number"><span>{card.pickCount}</span></span></div>
      </div>
  } else if (card.pickCount !== 1) {
    drawPick =
      <div className="draw-pick">
        <div>PICK <span className="number"><span>{card.pickCount}</span></span></div>
      </div>
  }
  const processedCardText = processCardText(card.text, true)

  return (
    <div className="black card" style={{width: `${200 * scale}px`, height: `${200 * scale}px`}} data-bs-theme="light" key={uniqueId()}>
      <Textfit
        className="textfit text"
        max={18}
        min={12}
      >
        {processedCardText}
      </Textfit>
      <div className="bottom">
        <div className="pack-name">{card.packName}</div>
        {drawPick}
      </div>
    </div>
  )
}

interface WhiteCardViewProps extends CardProps<WhiteCard> {
  disabled?: boolean
  onClick?: () => void
}

export const WhiteCardView = ({ card, disabled, scale, onClick }: WhiteCardViewProps) => {

  if (scale === undefined)
    scale = 1

      //<div className="text" style={{fontSize: `${textSize * scale}px`}}>
  return (
    // everything scales relative to the fontSize on the card
    (<div
      className={`white card ${disabled ? "disabled" : ""}`}
      data-bs-theme="light"
      style={{fontSize: `${100 * scale}px`}}
      onClick={onClick}>
      <Textfit
        className="textfit text"
        max={18}
        min={4}
      >
        {processCardText(card.text, false)}</Textfit>
      <div className="bottom">
        <div className="pack-name">{card.packName}</div>
      </div>
    </div>)
  );
}

interface WhiteCardPlaceholderProps {
  active?: boolean
  text: string
  scale?: number
  onClick?: () => void
}

export const WhiteCardPlaceholder = ({ active, text, scale, onClick }: WhiteCardPlaceholderProps) => {
  if (scale === undefined)
    scale = 1

  return (
    <div
      className={`placeholder white card ${active ? "selected" : ""}`}
      style={{fontSize: `${100 * scale}px`}}
      onClick={onClick}>
      <div className="text">{text}</div>
    </div>
  )
}

interface WhiteCardGroupProps {
  cards: any[]
  active?: boolean
  actions?: any
  scale?: number
  onClick?: () => void
}

export const WhiteCardGroup = ({ cards, active, actions, scale, onClick }: WhiteCardGroupProps) => {
  if (scale === undefined)
    scale = 1

  return (
    <div
      className={`group ${cards.length > 1 ? "multi" : ""} ${active ? "selected" : ""}`}
      style={{fontSize: `${100 * scale}px`}}>
      <div className="group-cards" onClick={onClick}>
        {cards}
      </div>
      {actions && <div className="actions">{actions}</div>}
    </div>
  )
}
/* vim: set ft=typescriptreact : */
